# Generated by Django 4.0.4 on 2022-06-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='new',
        ),
    ]
